CREATE TABLE IF NOT EXISTS tb_estudante (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  curso VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  telefone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);